### PR TITLE
Refactor js

### PR DESCRIPTION
**Pull request by complikatyed**
Updated per Greg's comments.

Thanks for the input, Greg!

### CODE REVIEW

**Comment by gregkorte** [comment]
Nice Katye! :+1: 

More bonus: A couple more bonus items for you. First, try to get the inputs to clear automatically once the input is accepted and the tree is built. Second, restrict the number of allowable characters to one.

**Comment by gregkorte** [comment]
Hey Katye. Close! Looks like I'm still able to enter more than one character.

**Comment by complikatyed** [comment]
Greg,

Whoops.  I misunderstood what you were asking me to do.  I only put a guard
on the number input field, not on the character field, too.  I'll go back
and fix that later today.

Thanks!

Katye

**Comment by complikatyed** [comment]
Greg, I've added the last bonus piece.  Sorry, I forgot it was still floating out there.

**Pull request merged**
